yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]
handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.server_error'
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models import SET_NULL
from django.utils.text import Truncator

MAX_LEN_TEXT = 3
User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        'Здесь будет информация о группах проекта', max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return Truncator(self.title).words(MAX_LEN_TEXT)


class Post(models.Model):
    text = models.TextField(
        help_text='Текст нового поста'
    )
    pub_date = models.DateTimeField(
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        null=True,
        blank=True,
        on_delete=SET_NULL,
        related_name='posts',
        help_text='Группа, к которой относится пост',
        verbose_name='Группа'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return Truncator(self.text).words(MAX_LEN_TEXT)


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        null=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="comments",
        null=True
    )
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="follower"
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="following"
    )

yatube/posts/forms.py
from django import forms
from django.contrib.auth import get_user_model

from .models import Comment, Post

User = get_user_model()


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('group', 'text', 'image')
        labels = {
            'group': 'Группа',
            'text': 'Текст',
            'image': 'Изображение'
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("text",)
        widgets = {
            'text': forms.Textarea(),
        }
        labels = {
            "text": "Текст"
        }

yatube/posts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect

from .forms import CommentForm, PostForm
from .models import Follow, Post, Group
from .utils import get_page_context

User = get_user_model()


def index(request):
    page_obj = get_page_context(Post.objects.all(), request)
    context = {'page_obj': page_obj}
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    page_obj = get_page_context(group.posts.all(), request)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    user = request.user
    page_obj = get_page_context(author.posts.all(), request)
    following = Follow.objects.filter(
        user__username=user, author=author
    ).count()
    context = {
        'author': author,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm()
    comments = post.comments.select_related('author')
    context = {
        'post': post,
        'form': form,
        'comments': comments
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )
    if not request.method == 'POST':
        return render(request, 'posts/post_create.html', {'form': form})
    if not form.is_valid():
        return render(request, 'posts/post_create.html', {'form': form})
    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('posts:profile', username=post.author.username)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post.pk)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post.pk)
    return render(request, 'posts/post_create.html',
                  {'form': form, "is_edit": True})


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post.pk)


@login_required
def follow_index(request):
    page_obj = get_page_context(
        Post.objects.filter(author__following__user=request.user), request
    )
    context = {'page_obj': page_obj}
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    profile_follow_new = Follow.objects.filter(
        author=author, user=request.user
    )
    if profile_follow_new.exists():
        profile_follow_new.delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/follow.html
{% extends 'base.html' %}

{% block title %}
    Последние обновления
{% endblock %}
{% load cache %}
{% block content %}
    {% include 'includes/switcher.html' %}
    <article>
        {% cache 20 index_page with page_obj %}
            {% for post in page_obj %}
                {% include 'includes/post_card.html' %}
            {% endfor %}
        {% endcache %}
    </article>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block title %}
    {{ group.title }}
{% endblock %}

{% block content %}
    <h1>{{ group.title }}</h1>
    <p>{{ group.description }}</p>
    {% for post in page_obj %}
        {% include 'includes/post_card.html' %}
    {% endfor %}
    {% if not forloop.last %}
        <hr>{% endif %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
    Последние обновления на сайте
{% endblock %}
{% load cache %}
{% block content %}
    {% include 'includes/switcher.html' %}
<article>
    {% cache 20 index_page with page_obj %}
    {% for post in page_obj %}
        {% include 'includes/post_card.html' %}
    {% endfor %}
{% endcache %}
</article>
{% endblock %}

yatube/templates/posts/post_create.html
{% extends 'base.html' %}
{% load user_filters %}

{% block content %}
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-md-8 p-5">
                <div class="card">
                    <div class="card-header">
                        Новый пост
                    </div>
                    <div class="card-body">
                        {% if form.errors %}
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <div class="alert alert-danger">{{ error|escape }}</div>
                                {% endfor %}
                            {% endfor %}
                            {% for error in form.non_field_errors %}
                                <div class="alert alert-danger">{{ error|escape }}</div>
                            {% endfor %}
                        {% endif %}
                        <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group row my-3"
                                 {% if field.field.required %} aria-required="true" {% else %} aria-required="false" {% endif %}>
                                <label for="{{ field.id_for_label }}">
                                    {{ field.label }}
                                    {% if field.field.required %}<span class="required text-danger">*</span>{% endif %}
                                </label>
                                <div>
                                    {{ field|addclass:'form-control' }}
                                    {% if field.help_text %}
                                        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                                    {% endif %}
                                </div>
                            </div>
                        {% endfor %}
                            <div class="d-flex justify-content-end">
                                <button type="submit" class="btn btn-primary">
                                    {% if is_edit %}
                                        Сохранить
                                    {% else %}
                                        Добавить
                                    {% endif %}
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %} {{ post|truncatewords:30 }} {% endblock %}
{% load thumbnail %}
{% block content %}
    <body>
    <main>
        <div class="row">
            <aside class="col-12 col-md-3">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        Дата публикации: {{ post.pub_date|date:"d E Y" }}
                    </li>
                    {% if post.group and not group %}
                        <li class="list-group-item">
                            Группа: {{ post.group.title }}
                        </li>
                        <li class="list-group-item">
                            <a href="{% url 'posts:group_list' post.group.slug %}">все
                                записи группы</a>
                            <br>
                        </li>
                    {% endif %}
                    </li>
                    <li class="list-group-item">
                        Автор: {{ post.author.first_name }} {{ post.author.last_name }}
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        Всего постов автора:
                        <span>{{ post.author.posts.count }}</span>
                    </li>
                    <li class="list-group-item">
                        <a href="{% url 'posts:profile' post.author %}">
                            все посты пользователя
                        </a>
                    </li>
                </ul>
            </aside>
            <article class="col-12 col-md-9">
                {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                    <img class="card-img my-2" src="{{ im.url }}">
                {% endthumbnail %}
                {{ post.text|linebreaks }}
                {% if user == post.author %}
                    <div class="row justify-content-center">
                        <a class="btn btn-primary"
                           href="{% url 'posts:post_edit' post.pk %}">редактировать
                            запись</a>
                    </div>
                {% endif %}
            {% include 'includes/comments.html' with post=post items=post.comments.all form=form %}
            </article>
        </div>
    </main>
    </body>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
    Профайл пользователя {{ author.first_name }} {{ author.last_name }}
{% endblock %}
{% block content %}
    <div class="mb-5">
        <h1>Все посты
            пользователя: {{ author.first_name }} {{ author.last_name }} </h1>
        <h3>Всего постов: {{ author.posts.count }} </h3>
    {% if user != author %}
        {% if following %}
            <a
                    class="btn btn-lg btn-light"
                    href="{% url 'posts:profile_unfollow' author.username %}"
                    role="button"
            >
                Отписаться
            </a>
        {% else %}
            <a
                    class="btn btn-lg btn-primary"
                    href="{% url 'posts:profile_follow' author.username %}"
                    role="button"
            >
                Подписаться
            </a>
        {% endif %}
    {% endif %}
    </div>
    <article>
        {% for post in page_obj %}
            {% include 'includes/post_card.html' %}
        {% endfor %}
    </article>
{% endblock %}